### ISSUE TITLE
BUG reload page V.2 in DEMO page and when using

### ISSUE THREAD

**Issue by choonoi** [nyroDev/nyroModal#14] opened 2011-01-13 11:13 UTC
I'm using Firefox , IE6 ,IE 7 , IE 8 and get error.
when i click link to open modal ajax and I click link in that modal to open new page or reload in modal it's not reload or not working if click same link and found error.

Webpage error details

Message: 'data(...).elts' is null or not an object
Line: 225
Char: 6
Code: 0
URI: http://localhost/java/nyroModal/js/jquery.nyroModal.custom.js

----------- the error line is --------
if (!this.stack && this.getInternal().stack.length > 1)
    this.elts = $(_internal.stack[_internal.stack.length-2]).data('nmObj').elts; <--

Thank you for great Modal

**Comment by nyroDev** [comment] 2011-01-13 12:32
Even if I understand the problem, I can't reproduce it.
Could you tell me how you to reproduce it please?

**Comment by choonoi** [comment] 2011-01-13 16:22
I just remove that 2 lines then it work fine for me. 
but I dont understand well what is that line for?

**Comment by nyroDev** [comment] 2011-01-13 16:23
This line is about stacking. They are useful when you want not stackable modal in order to use the same HTML elts for a new modal

**Comment by choonoi** [comment] 2011-01-13 19:22
how about if i change that line like this ?

this.elts = $(_internal.stack[_internal.stack.length-1]).data('nmObj').elts; 

getInternal().stack.length >1 so how about if just -1 
because if - 2 it will be empty ?

i did not check all code because i really don't understand much about it.

but it also work fine just -1 "_internal.stack[_internal.stack.length" so 
data('nmObj') will not null or empty. am i right?

**Comment by andrelaszlo** [comment] 2011-01-18 16:08
I had the same problem and choonois solution worked for me as well. I'm not using stacking.

**Comment by andrelaszlo** [comment] 2011-01-18 16:08
Also, the bug doesn't seem to be browser specific.

**Comment by nyroDev** [comment] 2011-01-22 14:32
Could someone tell me exactly how can I reproduce this bug please?
the code mentionned here was added to fix a bug, so it should stay here.

**Comment by andrelaszlo** [comment] 2011-01-22 23:03
The bug is reproduced here: http://andre.laszlo.nu/nyroModal/issue14.html
Download the code as a zip file here: http://andre.laszlo.nu/nyroModal/issue14.zip

**Comment by adrianoh** [comment] 2011-02-24 20:40
This error is reproduced here too: http://nyromodal.nyrodev.com/ in the example: "simple form filtering content" button, when windows apear, click en "new modal", and in new windows,  click in button "new modal from a form". The error is here.

**Comment by adrianoh** [comment] 2011-02-24 20:58
In the "simple form" example, from http://nyromodal.nyrodev.com/ error is reproduced too.

**Comment by nyroDev** [comment] 2011-02-25 17:39
Update documentation in Readme file
Add swfObjectId settings and use it in filters.swf or create an uniq ID. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add recalc settings for nm.resize function to force the recalculation of the modal. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix issue with jQuery 1.5 on IE8 (bogus selector in filters.swf). Closed by 3fafa309866755b1397617bae595353c276a4a88
Fix stack error when reopening a modal. Closed by 3fafa309866755b1397617bae595353c276a4a88
Add initFilters callbacks in order to force filters. Closed by 3fafa309866755b1397617bae595353c276a4a88 Closes#37
Add afterReposition and afterUnreposition callbacks.

**Closed as completed by nyroDev** 2011-02-25 17:39 UTC
